### ISSUE TITLE
Tensorboard

### ISSUE THREAD

**Issue by CONGLUONG12** [hayeong0/DDDM-VC#15]
Hello, Thanks for your great work!
In the paper, you write that you have trained F0 VQVAE model,I also want to train this model with my dataset in another language. So, can you share the tensorboard when training this model? 
Thank you.

**Comment by hayeong0** [comment]
Hello, thank you for showing interest in our work.

I have reviewed the issue and checked the Tensorboard logs, but unfortunately, since the work was done during my master's program in the lab, only the checkpoints for the F0 VQ-VAE model were preserved and the Tensorboard logs were not backed up.  
If you encounter any issues or difficulties while training the model in your environment, please leave additional comments and I will do my best to assist you. 

Good luck with your research!
