### ISSUE TITLE
"Invalid Value Encountered in Divide" when running preprocessing code. 

### ISSUE THREAD

**Issue by cryptowooser** [hayeong0/DDDM-VC#9]
Hello,

I'm encountering the following runtime warning when running the preprocessing code against my dataset. This appears to show up for every wav I throw at it, and these wavs are typical 16khz so I'm not sure what the issue might be. 

/home/gradientascent/miniconda3/envs/DDDM-VC-2/lib/python3.9/site-packages/amfm_decompy/pYAAPT.py:970: RuntimeWarning: invalid value encountered in divide
  phi[lag_min:lag_max] = formula_nume/np.sqrt(formula_denom)

Is this a known issue?

**Comment by hayeong0** [comment]
Hello,

It seems that this warning occurs when using the YAAPT algorithm to extract F0. 
Could you let me know what type of data you are using? 
This issue is likely to arise if 1) there are significant periods of silence in the audio, or 2) the audio signal has a low volume.
I have encountered this warning with singing data or real-world samples. 
Normalizing the audio to a consistent scale might help mitigate the problem :)
